// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcHeB_EmXXq3CjKY7-t97KYmRPCoWU6EM',
    appId: '1:900920637251:web:69e9acdafa9794837d21f6',
    messagingSenderId: '900920637251',
    projectId: 'flutter-shopping-a257c',
    authDomain: 'flutter-shopping-a257c.firebaseapp.com',
    storageBucket: 'flutter-shopping-a257c.appspot.com',
    measurementId: 'G-63QEYFG249',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-YLMN1DWMmPtWQKNxF8IRHSzW7xWwc3Y',
    appId: '1:900920637251:android:2988161fcc8871787d21f6',
    messagingSenderId: '900920637251',
    projectId: 'flutter-shopping-a257c',
    storageBucket: 'flutter-shopping-a257c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGZWTF0k_WN0z-TXb0l61KRxLX4fE2H8U',
    appId: '1:900920637251:ios:ab2ba5a18a3f960c7d21f6',
    messagingSenderId: '900920637251',
    projectId: 'flutter-shopping-a257c',
    storageBucket: 'flutter-shopping-a257c.appspot.com',
    iosClientId: '900920637251-b9qvu7omc95ebmnsf9makqklfnp3sn0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterShopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGZWTF0k_WN0z-TXb0l61KRxLX4fE2H8U',
    appId: '1:900920637251:ios:b7e910b3ee1840c57d21f6',
    messagingSenderId: '900920637251',
    projectId: 'flutter-shopping-a257c',
    storageBucket: 'flutter-shopping-a257c.appspot.com',
    iosClientId: '900920637251-hlnoehlr4eccl306as3ss9633jq3gn6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterShopping.RunnerTests',
  );
}
